# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 0) do

  create_table "fellowships", :force => true do |t|
    t.column "created_on", :date, :null => false
    t.column "updated_on", :date, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "category", :string, :default => "", :null => false
    t.column "leader", :integer, :default => 0, :null => false
    t.column "hours", :integer, :default => 0, :null => false
    t.column "title", :string, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "directions", :text, :default => "", :null => false
    t.column "car_needed", :integer, :default => 0, :null => false
    t.column "auto_needed", :integer, :default => 0, :null => false
  end

  create_table "fundraisers", :force => true do |t|
    t.column "created_on", :date, :null => false
    t.column "updated_on", :date, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "category", :string, :default => "", :null => false
    t.column "leader", :integer, :default => 0, :null => false
    t.column "hours", :integer, :default => 0, :null => false
    t.column "title", :string, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "directions", :text, :default => "", :null => false
    t.column "car_needed", :integer, :default => 0, :null => false
    t.column "auto_needed", :integer, :default => 0, :null => false
  end

  create_table "hours", :force => true do |t|
    t.column "created_on", :text, :default => "", :null => false
    t.column "updated_on", :integer, :default => 0, :null => false
    t.column "updated_by", :integer, :default => 0, :null => false
    t.column "event_type", :integer, :default => 0, :null => false
    t.column "project_id", :integer, :default => 0, :null => false
    t.column "fundraiser_id", :integer, :default => 0, :null => false
    t.column "fellowship_id", :integer, :default => 0, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "hour_type", :string, :default => "", :null => false
    t.column "hours", :integer, :default => 0, :null => false
  end

  create_table "newsletters", :force => true do |t|
    t.column "created_on", :date, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "file", :string, :default => "", :null => false
  end

  create_table "projects", :force => true do |t|
    t.column "created_on", :date, :null => false
    t.column "updated_on", :date, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "category", :string, :default => "", :null => false
    t.column "leader", :integer, :default => 0, :null => false
    t.column "hours", :integer, :default => 0, :null => false
    t.column "title", :string, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "directions", :text, :default => "", :null => false
    t.column "car_needed", :integer, :default => 0, :null => false
    t.column "auto_needed", :integer, :default => 0, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80, :default => "", :null => false
    t.column "salted_password", :string, :limit => 40, :default => "", :null => false
    t.column "email", :string, :limit => 60, :default => "", :null => false
    t.column "firstname", :string, :limit => 40
    t.column "lastname", :string, :limit => 40
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "verified", :integer, :default => 0
    t.column "role", :string, :limit => 40
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "logged_in_at", :datetime
    t.column "deleted", :integer, :default => 0
    t.column "delete_after", :datetime
  end

end
